services:
  - type: web
    name: axs-residencial
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: AXS_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///axs_v2.db
